version: '2.1'

services:

### Applications Code Container #############################

  #data: 
  #  image: tianon/true             # scratch base images are not working on AWS
  #  volumes:
  #    - ./data:/app/data           # shared volume for data and index mapping
  
  front:
    image: papernet-front:caddy-latest
    container_name: front
    build: 
      context: dist/front/papernet
      dockerfile: Dockerfile.caddy.alpine # or Dockerfile.alpine.nginx
    ports:
      - 8080:8080
    restart: unless-stopped
    command: ["/usr/bin/caddy", "-conf", "/etc/Caddyfile"]
    volumes:
      - ./data/papernet:/app/data
      - ./conf/certs:/app/conf
    networks:
     - default
    labels:
      - "org.label-schema.vendor=bobinette"
      - "org.label-schema.url=https://github.com/bobinette/papernet-front"
      - "org.label-schema.name=Papernet 'FRONT-END' - Production"
      - "org.label-schema.description=Front-end of the papernet project."
      - "org.label-schema.version=0.9.3"
      - "org.label-schema.docker.schema-version=1.0"
      - "papernet.component.group=frontend"
      - "papernet.component.type=dist"

  cli:
    image: papernet-backend-cli:alpine-dist
    container_name: papernet_cli
    build: 
      context: ./dist/cli/papernet
      dockerfile: Dockerfile.dist.alpine
    expose:
      - 1705
    entrypoint: /app/papernet_cli
    # command: ["index", "create", "--index=/app/data/papernet.index", "--mapping=/app/data/mapping.json"]
    networks:
      - default
    volumes:
      - ./data/papernet:/app/data
      - ./conf/certs:/app/conf
    labels:
      - "org.label-schema.vendor=bobinette"
      - "org.label-schema.url=https://github.com/bobinette/papernet"
      - "org.label-schema.name=Papernet 'BACK-END' CLI - Production"
      - "org.label-schema.description=Very simple tool to keep track of the papers you read."
      - "org.label-schema.version=0.9.1"
      - "org.label-schema.docker.schema-version=1.0"
      - "papernet.component.group=backend"
      - "papernet.component.type=dist"

  web:
    image: papernet-backend-web:alpine-dist
    container_name: papernet_web
    build: 
      context: ./dist/web/papernet
      dockerfile: Dockerfile.dist.alpine
    ports:
      - 1705:1705
    restart: unless-stopped
    entrypoint: /app/papernet_web
    networks:
      - default
    volumes:
      - ./data/papernet:/app/data
      - ./conf/certs:/app/conf
    labels:
      - "org.label-schema.vendor=bobinette"
      - "org.label-schema.url=https://github.com/bobinette/papernet"
      - "org.label-schema.name=Papernet 'BACK-END' WEB - Production"
      - "org.label-schema.description=Very simple tool to keep track of the papers you read."
      - "org.label-schema.version=0.9.1"
      - "org.label-schema.docker.schema-version=1.0"
      - "papernet.component.group=backend"
      - "papernet.component.type=dist"

### Networks Setup ############################################

#networks:
#  backend:
#    driver: "bridge"

### Volumes Setup #############################################

#volumes:
#  papernet_data:
#    driver: 'local'

