FROM mhart/alpine-node:6
# FROM mitcdh/caddy-nodejs
# FROM node:6.9.5-alpine

MAINTAINER Rosco Pecoltran <rosco.pecoltran@msn.com>

ARG GOSU_VERSION=${GOSU_VERSION:-"1.10"}

# List of packages that need to be installed for node_modules to compile
ARG APK_PACKAGES_BUILD=${APK_PACKAGES_BUILD:-"tar git curl make gcc g++ python linux-headers paxctl libgcc libstdc++"}

# List of additional/custom packages that need to be installed for running the container in an interactive mode.
ARG APK_PACKAGES_INTERACTIVE=${APK_PACKAGES_INTERACTIVE:-"bash nano tree"}

# List of additional/custom packages that need to be installed for node_modules to compile (eg.libjpeg,...)
ARG APK_PACKAGES_RUNTIME=${APK_PACKAGES_RUNTIME:-""}

# Simple Go-based setuid+setgid+setgroups+exec
ADD https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64 /usr/local/sbin/gosu

# Copy dependencies list
ADD package.json /code/package.json

# npm cache clean
RUN apk add --update --no-cache ${APK_PACKAGES_INTERACTIVE} ${APK_PACKAGES_RUNTIME} \
    && apk --no-cache add --virtual devs ${APK_PACKAGES_BUILD} \
    && curl --silent --show-error --fail --location \
        --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
        "https://caddyserver.com/download/linux/amd64?plugins=http.authz,http.cors,http.expires,http.git,http.ipfilter,http.minify,http.ratelimit,http.realip,http.upload,net,tls.dns.gandi,tls.dns.googlecloud,tls.dns.linode,tls.dns.ovh,tls.dns.route53" \
        | tar --no-same-owner -C /usr/bin/ -xz caddy \
    && mv /usr/bin/caddy /usr/bin/caddy \
    && chmod 0755 /usr/bin/caddy \
    && chmod +x /usr/local/sbin/gosu \
	&& adduser -D app -h /data -s /bin/sh \
	&& mkdir -p /code \
	&& cd /code \
    && npm install -g -s --no-progress yarn \
    && yarn install \
    && apk del --no-cache ${APK_PACKAGES_BUILD} \
    && apk --no-cache --no-progress del devs

WORKDIR /code
ADD . /code

RUN yarn run build \
    && mkdir -P /dist \
    && cp -Rf /code/app/* /dist/ \
    && yarn cache clean

VOLUME ["/dist"]
EXPOSE 8080

CMD ["/bin/bash"]